version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/client

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8888:8080
    volumes:
      - ./server:/api
    depends_on:
      - db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: fucalendar

  db:
    image: postgres:14-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fucalendar
    ports:
      - 5432:5432
